#define BARRIER_TYPE 1
#define BARRIER_X1 2
#define BARRIER_Y1 3
#define BARRIER_X2 4
#define BARRIER_Y2 5

#define BARRIER_CONTENT 5

#define BARRIER_TYPE_DIVIDER 1
#define BARRIER_TYPE_ONE_WAY_DIVIDER 2
#define BARRIER_TYPE_SOLID 3
#define BARRIER_TYPE_PREFERRED_PATH 4

#define PICK_SOLID_BARRIER 1
#define PICK_DIVIDER_NODE 2
#define PICK_DIVIDER_EDGE 3

#define WORKER_STATE_PROFILE 1

#define WORKER_STATE_TRAVEL 1
#define WORKER_STATE_PALLET_LOAD_UNLOAD 2
#define WORKER_STATE_CASE_PICKING 3
#define WORKER_STATE_LAYER_PICKING 4
#define WORKER_STATE_BUSY 5
#define WORKER_STATE_IDLE 6
#define WORKER_STATE_BREAK 7
#define WORKER_STATE_BUSY_BREAK 8
#define WORKER_STATE_IDLE_HELD 9

#define WORKER_STATE_CONTENT 9

#define EVENT_A_STAR_END_TRAVEL 1005

#define ITEM_TYPE_PALLET -1
#define ITEM_TYPE_TRUCK -2
#define ITEM_TYPE_CASE -3