#define BARRIER_TYPE 1
#define BARRIER_X1 2
#define BARRIER_Y1 3
#define BARRIER_X2 4
#define BARRIER_Y2 5

#define BARRIER_CONTENT 5

#define BARRIER_TYPE_DIVIDER 1
#define BARRIER_TYPE_ONE_WAY_DIVIDER 2
#define BARRIER_TYPE_SOLID 3
#define BARRIER_TYPE_PREFERRED_PATH 4

#define PICK_SOLID_BARRIER 1
#define PICK_DIVIDER_NODE 2
#define PICK_DIVIDER_EDGE 3

#define EVENT_A_STAR_END_TRAVEL 1005

#define EDITMODE_PREFERRED_PATH 35
#define EDITMODE_DIVIDER 36
#define EDITMODE_ONE_WAY_DIVIDER 37
#define EDITMODE_SOLID_BARRIER 38

#define ASTAR_DRAW_MODE_GRID 0x1
#define ASTAR_DRAW_MODE_BARRIERS 0x2
#define ASTAR_DRAW_MODE_TRAFFIC 0x4

#define PICK_TYPE_HIGHLIGHT_INFO_TRAVEL_GRID 203
